baseURL = "https://nervous-shockley-8d1c89.netlify.com/"
languageCode = "en-us"
title = "Dreamgrove"
copyright = "Dreamgrove"
theme = "ghostwriter"
buildDrafts = "true"
buildFuture = "true"

[Taxonomies]
  tag = "tags"
