baseURL = "https://vigilant-fermi-011301.netlify.com/"
languageCode = "en-us"
title = "Dreamgrove"
copyright = "Dreamgrove"
theme = "dg-theme"
buildDrafts = "true"
buildFuture = "true"

[Taxonomies]
  tag = "tags"
  spec = "specs"
