baseURL = "https://nervous-shockley-8d1c89.netlify.com/"
languageCode = "en-us"
title = "Dreamgrove"
copyright = "Dreamgrove"
theme = "dg-theme"
buildDrafts = "true"
buildFuture = "true"

[blackfriday]
  hrefTargetBlank = true

[params]
  description = "Home of all things Druid"
  restoExternalURL = "http://questionablyepic.com"

[taxonomies]
  spec = "specs"
