baseURL = "https://www.dreamgrove.gg/"
languageCode = "en-us"
title = "Dreamgrove"
copyright = "Dreamgrove"
theme = "dg-theme"
buildDrafts = "false"
buildFuture = "false"

[Taxonomies]
  tag = "tags"

[taxonomies]
  spec = "specs"
