languageCode = "en-us"
title = "Dreamgrove"
copyright = "Dreamgrove"
theme = "dg-theme"

[blackfriday]
  hrefTargetBlank = true

[params]
  description = "Dreamgrove is the home of all things Druid. Guides, articles, theorycrafting, and more!"
  restoExternalURL = "http://questionablyepic.com"

[taxonomies]
  series = "series"
