# This is a basic workflow that is manually triggered

name: Generate Sims

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: static/beta

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: update python
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: talent sims
        run: python generate_by_talent.py
      - name: 1 target combo
        run: python generate_by_combo.py -t 1
      - name: 2 target combo
        run: python generate_by_combo.py -t 2
      - name: 3 target combo
        run: python generate_by_combo.py -t 3
      - name: 4 target combo
        run: python generate_by_combo.py -t 4
      - name: 5 target combo
        run: python generate_by_combo.py -t 5
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update sims
